mysql:
  container_name: docker_mysql
  image: mysql:8.0
  environment:
    #- "TZ=Asia/Tokyo"
    - "MYSQL_ROOT_HOST=%"
    - "MYSQL_ROOT_PASSWORD=root"
  volumes:
    - mysql:/var/lib/mysql
    - ./etc/my.cnf:/etc/my.cnf
    - ./sql:/docker-entrypoint-initdb.d
  ports:
    - "3306:3306"
